### ISSUE TITLE
Debug issue

### ISSUE THREAD

**Issue by kierenblack** [thomaslaurenson/Dragino_LoRaShield_Node_AU915#1]
I had an issue when LMIC_DEBUG_LEVEL was greater than 1.  It was line 118 
```
lmic_printf("%lu: Running job %p, cb %p, deadline %lu\n", os_getTime(), j, j->func, is_runnable? j->deadline : 0);
```
The is_runnable wasn't declared. I had to copy the original file from https://github.com/matthijskooijman/arduino-lmic/blob/master/src/lmic/oslmic.c.

**Comment by thomaslaurenson** [comment]
Hey Kieren, thanks for letting me know of the issue. I have updated the repository to align with the latest commits from the original Arduino-LMIC library. The latest commit (31d28d5a1141d7caf94db1731772779fd21d5cda) should fix this issue as it implements the same change you documented.
